// <auto-generated />
using System;
using AlmacenWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlmacenWeb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251102172427_VentasYDetalles")]
    partial class VentasYDetalles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AlmacenWeb.Models.Cliente", b =>
                {
                    b.Property<int>("ClId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClId"));

                    b.Property<string>("ClApellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ClDireccion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ClDniCuit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ClEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ClNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ClTelefono")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ClId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("AlmacenWeb.Models.DetalleVenta", b =>
                {
                    b.Property<int>("DeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeId"));

                    b.Property<int>("DeCantidad")
                        .HasColumnType("int");

                    b.Property<decimal>("DePrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DeSubtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PrId")
                        .HasColumnType("int");

                    b.Property<int>("VeId")
                        .HasColumnType("int");

                    b.HasKey("DeId");

                    b.HasIndex("PrId");

                    b.HasIndex("VeId");

                    b.ToTable("DetalleVenta");
                });

            modelBuilder.Entity("AlmacenWeb.Models.Producto", b =>
                {
                    b.Property<int>("PrId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrId"));

                    b.Property<int>("CantidadDisponible")
                        .HasColumnType("int");

                    b.Property<string>("CodigoBarra")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PrNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PrId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("AlmacenWeb.Models.Rol", b =>
                {
                    b.Property<int>("RoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoId"));

                    b.Property<string>("RoDescripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RoNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("AlmacenWeb.Models.Usuario", b =>
                {
                    b.Property<int>("UsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsId"));

                    b.Property<int>("RoId")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("UsActivo")
                        .HasColumnType("bit");

                    b.Property<string>("UsApellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UsFechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("UsNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsPassword")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("date_created")
                        .HasColumnType("datetime2");

                    b.HasKey("UsId");

                    b.HasIndex("RoId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("AlmacenWeb.Models.Venta", b =>
                {
                    b.Property<int>("VeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VeId"));

                    b.Property<int>("ClId")
                        .HasColumnType("int");

                    b.Property<int>("UsId")
                        .HasColumnType("int");

                    b.Property<DateTime>("VeFecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("VeTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("VeId");

                    b.HasIndex("ClId");

                    b.HasIndex("UsId");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("AlmacenWeb.Models.DetalleVenta", b =>
                {
                    b.HasOne("AlmacenWeb.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("PrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlmacenWeb.Models.Venta", "Venta")
                        .WithMany("DetalleVentas")
                        .HasForeignKey("VeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("AlmacenWeb.Models.Usuario", b =>
                {
                    b.HasOne("AlmacenWeb.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("AlmacenWeb.Models.Venta", b =>
                {
                    b.HasOne("AlmacenWeb.Models.Cliente", "Cliente")
                        .WithMany("Ventas")
                        .HasForeignKey("ClId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlmacenWeb.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AlmacenWeb.Models.Cliente", b =>
                {
                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("AlmacenWeb.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("AlmacenWeb.Models.Venta", b =>
                {
                    b.Navigation("DetalleVentas");
                });
#pragma warning restore 612, 618
        }
    }
}
